/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export enum RoutesAPI {
  login = "/user/login",
  register = "/user/register",
  registerNutri = "/user/register/nutri",
  requestReset = "/reset/request",
  resetPWD = "/reset/",
  about = "/",
  publish = "/post/",
  profile = "/profile/",
  simpleProfile = "/profile/s/",
  unfollow = "/unfollow/",
  follow = "/follow/",
  updateProfile = "/profile/",
  getConfigPrivacy = "/profile/config/privacy",
  updateConfigPrivacy = "/profile/config",
  getMyPostForEditAPI = "/post/",
  removeMyPost = "/post/",
  updatePost = "/post/",
  likeRoute = "/post/like/",
  simplePost = "/post/s/",
  comment = "/comment/",
  marked = "/marked/",
  unmarked = "/marked/",
  foryou = "/home/foryou",
  followHome = "/home/follow",

  getComments = "/comment/",
  planInsert = "/plan",
  planEdit = "/plan",
  planDelete = "/plan/",
  planList = "/plan/",
  planMarked = "/plan/",
  getHours = "/hours/",
  overview = "/hours/overview/data",

  createHours = "/hours/",
  deleteHours = "/hours/",
  updateHours = "/hours/",
  listSimpleNutri = "/nutri/",
  markHour = "/nutri/mark",
  getServices = "/nutri/services",
  getServicesNutri = "/nutri/myServices",
  GetRevenues = "/revenue/",
  getConfig = "/nutri/configs",
  updateConfigNutri = "/nutri/configs",

  getRevenueUser = "/revenue/user/",
  deleteRevenue = "/revenue/",
  updateRevenue = "/revenue/",
  createRevenue = "/revenue/",
  createRevenueUser = "/revenue/user/",
}

export enum Routes {
  home = "/home",
  login = "/login",
  register = "/register",
  profile = "/profile",
  post = "/post?id=",
  nutri = "/nutri",
}
