import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/fonts.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    prefix: "Nutrify ",
  },
  icons: "@/favincon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div style={{ position: "relative", zIndex: "10" }} id="alert-container"></div>
      </body>
    </html>
  );
}
